### ISSUE TITLE
Opera start page

### ISSUE THREAD

**Issue by EC-O-DE** [mubaidr/Better-Speeddial#1]
They do support - but they are in process currently and at the moment and for quite some time with Reborn UI / features.

While one doesn't want to do Start Page / SD overhaul anytime soon - one can make extensions that utilize speed dials and/or speed dial folders.

mubaidr I think u have huge potential to be _great_ Opera addon dev :) ;)

**Comment by mubaidr** [comment]
Good to hear, once i get confirmation news i will definitely try to launch a similar (or revamp this one) extension/addon. In the meantimeI will try to get more information about this feature. 

Thank you for your kind words. My only purpose to develop addons for Opera is to enhance/ease browsing experience in any possible way. Always looking for ideas which could be useful.

**Comment by EC-O-DE** [comment]
This ext is a great example of fine start page / speed dial ext. It works albeit not updated since 2014. Has minor issues. But very usable and great ext although could use extra features.
https://addons.opera.com/en/extensions/details/photo-tagger/?display=en
